//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtoV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asiakasluokittelu
    {
        public int LuokitteluID { get; set; }
        public bool Eläkeläisalennus { get; set; }
        public bool Tv { get; set; }
        public bool Pöytäkone { get; set; }
        public bool Kannettava { get; set; }
        public bool Matkapuhelin { get; set; }
        public bool Tabletti { get; set; }
        public bool Mokkula { get; set; }
        //public Nullable<bool> Wlan { get; set; }
        public bool Wlan { get; set; }
        public int Asiakasnumero { get; set; }
    
        public virtual AsiakkaanPerustiedot AsiakkaanPerustiedot { get; set; }
    }
}
