//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtoV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asiakastapahtumat
    {
        public int TapahtumaID { get; set; }
        public int Asiakasnumero { get; set; }
        public System.DateTime Päivämäärä { get; set; }
        public string Yhteydenotto { get; set; }
        public string Kuvaus { get; set; }
        public string Ratkaisu { get; set; }
    
        public virtual AsiakkaanPerustiedot AsiakkaanPerustiedot { get; set; }
    }
}
