//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtoV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laskutustiedot
    {
        public int LaskutustietoID { get; set; }
        public int Asiakasnumero { get; set; }
        public string Etunimi { get; set; }
        public string Sukunimi { get; set; }
        public string Puhelin { get; set; }
        public string Osoite { get; set; }
        public string Postinumero { get; set; }
        public string Sähköposti { get; set; }
    
        public virtual AsiakkaanPerustiedot AsiakkaanPerustiedot { get; set; }
    }
}
