//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtoV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postitoimipaikat
    {
        public Postitoimipaikat()
        {
            this.AsiakkaanPerustiedot = new HashSet<AsiakkaanPerustiedot>();
        }
    
        public string Postinumero { get; set; }
        public string Postitoimipaikka { get; set; }
    
        public virtual ICollection<AsiakkaanPerustiedot> AsiakkaanPerustiedot { get; set; }
    }
}
