//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtoV1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SenioritEntities : DbContext
    {
        public SenioritEntities()
            : base("name=SenioritEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Asiakasluokittelu> Asiakasluokittelu { get; set; }
        public DbSet<Asiakastapahtumat> Asiakastapahtumat { get; set; }
        public DbSet<AsiakkaanPerustiedot> AsiakkaanPerustiedot { get; set; }
        public DbSet<Laskutustiedot> Laskutustiedot { get; set; }
        public DbSet<Logins> Logins { get; set; }
        public DbSet<Postitoimipaikat> Postitoimipaikat { get; set; }
    }
}
